try:
	print('raising')
	raise Exception('hello world')
except:
	print('caught')
